/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.java.gradle;

import com.example.CustomLogger;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        CustomLogger logger = new CustomLogger();
        logger.doIt();
    }
}
